/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthFinishRouteImport } from './routes/auth/finish'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleAccountRouteImport } from './routes/console/account'
import { Route as ConsoleHomeRouteImport } from './routes/console/home'
import { Route as ConsoleLogbookRouteImport } from './routes/console/logbook'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthLoginIdOtpRouteImport } from './routes/auth/login.$id/otp'
import { Route as AuthSignupIdOtpRouteImport } from './routes/auth/signup/$id/otp'
import { Route as AuthSignupIdTermsRouteImport } from './routes/auth/signup/$id/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthFinishRoute = AuthFinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAccountRoute = ConsoleAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleHomeRoute = ConsoleHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleLogbookRoute = ConsoleLogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIdOtpRoute = AuthLoginIdOtpRouteImport.update({
  id: '/login/$id/otp',
  path: '/login/$id/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupIdOtpRoute = AuthSignupIdOtpRouteImport.update({
  id: '/signup/$id/otp',
  path: '/signup/$id/otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupIdTermsRoute = AuthSignupIdTermsRouteImport.update({
  id: '/signup/$id/terms',
  path: '/signup/$id/terms',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/auth/finish': typeof AuthFinishRoute
  '/console/account': typeof ConsoleAccountRoute
  '/console/home': typeof ConsoleHomeRoute
  '/console/logbook': typeof ConsoleLogbookRoute
  '/auth/': typeof AuthIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/login/$id/otp': typeof AuthLoginIdOtpRoute
  '/auth/signup/$id/otp': typeof AuthSignupIdOtpRoute
  '/auth/signup/$id/terms': typeof AuthSignupIdTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/finish': typeof AuthFinishRoute
  '/console/account': typeof ConsoleAccountRoute
  '/console/home': typeof ConsoleHomeRoute
  '/console/logbook': typeof ConsoleLogbookRoute
  '/auth': typeof AuthIndexRoute
  '/console': typeof ConsoleIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/login/$id/otp': typeof AuthLoginIdOtpRoute
  '/auth/signup/$id/otp': typeof AuthSignupIdOtpRoute
  '/auth/signup/$id/terms': typeof AuthSignupIdTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/auth/finish': typeof AuthFinishRoute
  '/console/account': typeof ConsoleAccountRoute
  '/console/home': typeof ConsoleHomeRoute
  '/console/logbook': typeof ConsoleLogbookRoute
  '/auth/': typeof AuthIndexRoute
  '/console/': typeof ConsoleIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/login/$id/otp': typeof AuthLoginIdOtpRoute
  '/auth/signup/$id/otp': typeof AuthSignupIdOtpRoute
  '/auth/signup/$id/terms': typeof AuthSignupIdTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/console'
    | '/auth/finish'
    | '/console/account'
    | '/console/home'
    | '/console/logbook'
    | '/auth/'
    | '/console/'
    | '/auth/signup/'
    | '/auth/login/$id/otp'
    | '/auth/signup/$id/otp'
    | '/auth/signup/$id/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/finish'
    | '/console/account'
    | '/console/home'
    | '/console/logbook'
    | '/auth'
    | '/console'
    | '/auth/signup'
    | '/auth/login/$id/otp'
    | '/auth/signup/$id/otp'
    | '/auth/signup/$id/terms'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/console'
    | '/auth/finish'
    | '/console/account'
    | '/console/home'
    | '/console/logbook'
    | '/auth/'
    | '/console/'
    | '/auth/signup/'
    | '/auth/login/$id/otp'
    | '/auth/signup/$id/otp'
    | '/auth/signup/$id/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/finish': {
      id: '/auth/finish'
      path: '/finish'
      fullPath: '/auth/finish'
      preLoaderRoute: typeof AuthFinishRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/account': {
      id: '/console/account'
      path: '/account'
      fullPath: '/console/account'
      preLoaderRoute: typeof ConsoleAccountRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/home': {
      id: '/console/home'
      path: '/home'
      fullPath: '/console/home'
      preLoaderRoute: typeof ConsoleHomeRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/logbook': {
      id: '/console/logbook'
      path: '/logbook'
      fullPath: '/console/logbook'
      preLoaderRoute: typeof ConsoleLogbookRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/$id/otp': {
      id: '/auth/login/$id/otp'
      path: '/login/$id/otp'
      fullPath: '/auth/login/$id/otp'
      preLoaderRoute: typeof AuthLoginIdOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup/$id/otp': {
      id: '/auth/signup/$id/otp'
      path: '/signup/$id/otp'
      fullPath: '/auth/signup/$id/otp'
      preLoaderRoute: typeof AuthSignupIdOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup/$id/terms': {
      id: '/auth/signup/$id/terms'
      path: '/signup/$id/terms'
      fullPath: '/auth/signup/$id/terms'
      preLoaderRoute: typeof AuthSignupIdTermsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthFinishRoute: typeof AuthFinishRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthLoginIdOtpRoute: typeof AuthLoginIdOtpRoute
  AuthSignupIdOtpRoute: typeof AuthSignupIdOtpRoute
  AuthSignupIdTermsRoute: typeof AuthSignupIdTermsRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthFinishRoute: AuthFinishRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthLoginIdOtpRoute: AuthLoginIdOtpRoute,
  AuthSignupIdOtpRoute: AuthSignupIdOtpRoute,
  AuthSignupIdTermsRoute: AuthSignupIdTermsRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ConsoleRouteRouteChildren {
  ConsoleAccountRoute: typeof ConsoleAccountRoute
  ConsoleHomeRoute: typeof ConsoleHomeRoute
  ConsoleLogbookRoute: typeof ConsoleLogbookRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleAccountRoute: ConsoleAccountRoute,
  ConsoleHomeRoute: ConsoleHomeRoute,
  ConsoleLogbookRoute: ConsoleLogbookRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
